
###
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 114000
}

###
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001"
}

###
GET http://localhost:8080/account?user_id=1
Accept: application/json

###
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 3000
}

###
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "2fc1ef3ff97c4f22a20824ba16210b05",
  "accountNumber": "1000000001",
  "amount": 3000
}